@startuml

entity "districts" {
  * id : int <<PK>>
  --
  * name : varchar
}

entity "regions" {
  * id : int <<PK>>
  --
  * district_id : int <<FK>>
  --
  * name : varchar
}

entity "cities" {
  * id : int <<PK>>
  --
  * region_id : int <<FK>>
  --
  * name : varchar
}

entity "universities" {
  * id : int <<PK>>
  --
  * city_id : int <<FK>>
  --
  * name : varchar
}

entity "users" {
    * id : int <<PK>>
    --
    * university_id : int <<FK>>
    * city_id : int <<FK>>
    --
    * first_name : varchar
    * last_name : varchar
    * bio : TEXT
}

districts ||--o{ regions 
regions ||--o{ cities  
cities   ||--o{ universities 
users ||-- universities 
users ||-- cities 

@enduml

